---
title: 'Golden Crescent Performance Report BCY 23'
author:  
date: '`r  format.Date(Sys.Date(),format = "%d %B %Y")`'
output: 
  html_document:
    theme: "cerulean"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```


```{r C2GPS Logo}
htmltools::img(src = knitr::image_uri("H:/Reports/EWA/logo.png"), 
               alt = 'logo', 
               style = 'position:absolute; top:0; right:0; padding:10px; width: 120px; height: 60px') 
```

```{r Load Libraries}
library(tidyverse)  # data manipulation
library(readxl)     # read excel doc
library(lubridate)  # Lubridate provides tools that make it easier to parse
                    # and manipulate dates.
library(stringr)    # working with strings
library(kableExtra) # used to make tables
library(prettydoc)  # for the formatting of markdown reports
library(DT)         # used to make tables that can be downloaded
library(scales)     # used to format numbers to percent and dollar formats etc.
```


```{r  Source Functions}
source("C:/Users/casasxax/OneDrive - Workforce Solutions Southeast Texas/Performance Project/Functions/Functions.R")
```

```{r}
    # Fund and all funds are vectors we will use these to filter our extracts
funds <- c("Title I Adult - Local",
           "Title I DW - Local")

all_funds <- c("Title I Adult - Local",
               "Title I DW - Local",
               "Title I Youth - Local")
```

```{css Format}
h1 {color: #222d65;}
h2 {color: #162066;}
h3 {color: #238dc1;}
toc{color: #162066;}
body{font-size: 16px }
```


```{r Load Data}
setwd("C:\\Users\\casasxax\\OneDrive - C2\\Tableau Extracts\\Golden Crescent")
#set working directory to where you have the extracts
    # Reads the median earnings file
MEQ2 <- read_csv("MEQ2.csv")

MEQ2 <- MEQ2 %>% 
    filter(Denominator == 1) %>%
    distinct(`Twist Id`,Program,.keep_all = TRUE) %>% 
    mutate(Target = case_when(
        Program == "Title I Adult - Local" & `LWDA Number` == 19 ~ 7000,
        Program == "Title I Youth - Local" & `LWDA Number` == 19 ~ 3200,
        Program == "Title I DW - Local" & `LWDA Number`    == 19    ~ 9600,
        TRUE ~ 0),
        `Exit Date` = mdy_hm(`Exit Date`)) %>% 
    mutate("Exit Qtr" = case_when(
        `Exit Date` <= '2021-9-30' ~ "Q1",
        `Exit Date` <= '2021-12-31' ~ "Q2",
        `Exit Date` <= '2022-3-31' ~ "Q3",
        `Exit Date` <= '2022-6-30' ~ "Q4",
        TRUE ~ "Other"
    )) %>% 
    mutate(Numerator = Numerator %>% as.numeric(),
           Denominator = Denominator %>% as.numeric())

# Reads Employed enrolled quarter 4 data
EEQ4 <- read_csv("EEQ4.csv") %>% 
    mutate(`Board ID` = `Workforce Board Number`) %>% 
  filter(Program == "Title I Youth - Local") %>% 
  distinct(`Twist ID`, .keep_all = TRUE) %>% 
  mutate(`Exit Date`=mdy(`Exit Date`)) %>% 
    mutate(Quarter=case_when( `Exit Date` <= '2021-03-31' ~ "Q1",
                            `Exit Date` <= '2021-06-30' ~ "Q2",
                            `Exit Date` <= '2021-09-30' ~ "Q3",
                            TRUE ~ "Q4"),.after=`Exit Date`) %>% 
    filter(`Exit Date` >= '2021-01-01') %>% 
  mutate(Target=case_when(`Board ID` == 5  ~ 69.10,
                          `Board ID` == 18 ~ 66.70,
                          `Board ID` == 19 ~ 78.90,
                          `Board ID` == 20 ~ 0,
                          `Board ID` == 22 ~ 66.70,
                          `Board ID` == 23 ~ 66.70,
                          TRUE ~ 0))
         
EEQ2 <- read_csv("EEQ2.csv") %>% 
    mutate(`Board ID` = `Workforce Board Number`) %>% 
  filter(Program == "Title I Youth - Local") %>% 
  distinct(`Twist ID`, .keep_all = TRUE) %>% 
  mutate(`Exit Date`=mdy(`Exit Date`),
         Quarter=case_when(`Exit Date` <= '2021-09-30' ~ "Q1",
                           `Exit Date` <= '2021-12-31' ~ "Q2",
                           `Exit Date` <= '2022-03-31' ~ "Q3",
                           TRUE ~ "Q4"),.after=`Exit Date`) %>% 
  mutate(Target=case_when(`Board ID` == 5  ~ 72.70,
                          `Board ID` == 18 ~ 70.90,
                          `Board ID` == 19 ~ 70.40,
                          `Board ID` == 20 ~ 0,
                          `Board ID` == 22 ~ 70.70,
                          `Board ID` == 23 ~ 70.40,
                          TRUE ~ 0))

EEQ2_All <- read_csv("EEQ2.csv") %>% 
    mutate(`Board ID` = `Workforce Board Number`) %>%
  distinct(`Twist ID`, .keep_all = TRUE) %>% 
  mutate(`Exit Date`=mdy(`Exit Date`),
         Quarter=case_when(`Exit Date` <= '2021-09-30' ~ "Q1",
                           `Exit Date` <= '2021-12-31' ~ "Q2",
                           `Exit Date` <= '2022-03-31' ~ "Q3",
                           TRUE ~ "Q4"),.after=`Exit Date`) %>% 
  mutate(Target=case_when(`Board ID` == 5  ~ 72.70,
                          `Board ID` == 18 ~ 68.10,
                          `Board ID` == 19 ~ 68.10,
                          `Board ID` == 20 ~ 0,
                          `Board ID` == 22 ~ 70.70,
                          `Board ID` == 23 ~ 70.40,
                          TRUE ~ 0))


EQ2 <- read_csv("EQ2.csv") %>% 
    mutate(`Board ID` = `Workforce Board Number`) %>%
  filter(Program %in% funds) %>% 
  distinct(`Twist ID`,Program, .keep_all = TRUE) %>% 
  mutate(`Exit Date`=mdy(`Exit Date`),
          Quarter=case_when(`Exit Date` <= '2021-09-30' ~ "Q1",
                           `Exit Date` <= '2021-12-31' ~ "Q2",
                           `Exit Date` <= '2022-03-31' ~ "Q3",
                           `Exit Date` <= '2022-06-30' ~ "Q4",
                           TRUE ~ "Other"),.after=`Exit Date`) %>% 
  mutate(Target=case_when(`Board ID` == 5 & Program == "Title I Adult - Local" ~ 72.50,
                          `Board ID` == 5 & Program == "Title I DW - Local" ~ 78.80,
                          `Board ID` == 14 & Program == "Title I Adult - Local"~ 72.00,
                          `Board ID` == 14 & Program == "Title I DW - Local"~ 75.90,
                          `Board ID` == 18 & Program == "Title I Adult - Local"~ 72.00,
                          `Board ID` == 18 & Program == "Title I DW - Local"~ 85.00,
                          `Board ID` == 19 & Program == "Title I Adult - Local"~ 79.00,
                          `Board ID` == 19 & Program == "Title I DW - Local" ~ 77.50,
                          `Board ID` == 20 & Program == "Title I Adult - Local" ~ 72.00,
                          `Board ID` == 20 & Program == "Title I DW - Local" ~ 77.80,
                          `Board ID` == 22 & Program == "Title I Adult - Local"~ 72.60,
                          `Board ID` == 22 & Program == "Title I DW - Local"~ 77.60,
                          `Board ID` == 23 & Program == "Title I Adult - Local"~ 86.70,
                          `Board ID` == 23 & Program == "Title I DW - Local"~ 84.00,
                          TRUE ~ 0))

EQ4 <- read_csv("EQ4.csv") %>% 
    mutate(`Board ID` = `Workforce Board Number`) %>%
  filter(Program %in% funds) %>% 
  distinct(`Twist ID`,Program, .keep_all = TRUE) %>% 
  mutate(`Exit Date`=mdy(`Exit Date`),
          Quarter=case_when(`Exit Date` <= '2021-03-31' ~ "Q1",
                           `Exit Date` <= '2021-06-30' ~ "Q2",
                           `Exit Date` <= '2021-09-30' ~ "Q3",
                           `Exit Date` <= '2021-12-31' ~ "Q4",
                           TRUE ~ "Other"),.after=`Exit Date`) %>% 
  mutate(Target=case_when(`Board ID` == 5 & Program == "Title I Adult - Local" ~ 76.50,
                          `Board ID` == 5 & Program == "Title I DW - Local" ~ 83.60,
                          `Board ID` == 14 & Program == "Title I Adult - Local"~ 68.20,
                          `Board ID` == 14 & Program == "Title I DW - Local"~ 86.70,
                          `Board ID` == 18 & Program == "Title I Adult - Local"~ 72.80,
                          `Board ID` == 18 & Program == "Title I DW - Local"~ 80.90,
                          `Board ID` == 19 & Program == "Title I Adult - Local"~ 71.70,
                          `Board ID` == 19 & Program == "Title I DW - Local" ~ 86.70,
                          `Board ID` == 20 & Program == "Title I Adult - Local" ~ 73.30,
                          `Board ID` == 20 & Program == "Title I DW - Local" ~ 86.40,
                          `Board ID` == 22 & Program == "Title I Adult - Local"~ 76.40,
                          `Board ID` == 22 & Program == "Title I DW - Local"~ 81.70,
                          `Board ID` == 23 & Program == "Title I Adult - Local"~ 79.40,
                          `Board ID` == 23 & Program == "Title I DW - Local"~ 84.60,
                          TRUE ~ 0))

EEQ2_Q4 <- read_csv("EEQ2_Q4.csv") %>% 
    mutate(`Board ID` = `Workforce Board Number`) %>%
  filter() %>% 
  distinct(`Twist ID`,.keep_all = TRUE) %>% 
  mutate(`Exit Date`= mdy(`Exit Date`)) %>% 
    mutate(Quarter=case_when(`Exit Date` <= '2021-03-31' ~ "Q1",
                           `Exit Date` <= '2021-06-30' ~ "Q2",
                           `Exit Date` <= '2021-09-30' ~ "Q3",
                           TRUE ~ "Q4"),.after=`Exit Date`) %>% 
    filter(`Exit Date` >= '2021-01-01') %>% 
  mutate(Target=case_when(`Board ID` == 5 ~ 68.30,
                          `Board ID` ==14 ~ 70.70,
                          `Board ID` == 18 ~ 73.80,
                          `Board ID` == 19 ~ 69.90,
                          `Board ID` == 20 ~ 70.00,
                          `Board ID` == 22 ~ 68.30,
                          `Board ID` == 23 ~ 69.90,
                          TRUE ~ 0))

MSG <- read_csv("MSG.csv")
MSG <- MSG %>% 
    filter(Program %in% all_funds,
           `WDA Number` == 19) %>% 
  mutate(`MSG End Date` = mdy_hm(`MSG End Date`),
         MSG_END_DT = `MSG End Date`,
         "BOARD" == `WDA Number`) %>% 
    filter(MSG_END_DT >= '2022-07-01') %>% 
    mutate(Population_Desc = case_when(
        `Population Group Code` == 3 ~ "Youth",
        `Population Group Code` == 4 ~ "Adult",
        `Population Group Code` == 5 ~ "DW",
        TRUE ~ "Other"
    )) %>% 
    mutate(POPULATION = `Population Group Code`,
           WDA_NO = `WDA Number` %>% as.numeric(),
           `MSG Numerator` = `MSG Numerator` %>% as.numeric(),
           `MSG Denominator` = `MSG Denominator` %>% as.numeric()) %>% 
  mutate(Quarter = case_when(`MSG_END_DT` <= '2022-09-30' ~ "Q1",
                             `MSG_END_DT` <= '2022-12-31' ~ "Q2",
                             `MSG_END_DT` <= '2022-03-31' ~ "Q3",
                             TRUE ~ "Q4"),.after = `MSG_END_DT`) %>% 
    group_by(`Participation Period Id`, Program) %>%
    arrange(`Participation Period Id`, Program,desc(`MSG Numerator`)) %>%
    distinct(`Participation Period Id`, `Population Group Code`,.keep_all = TRUE) %>%
    ungroup()

credentials <- read_csv("Credential.csv")

credentials <- credentials %>% 
    mutate(Board = `Board Number`,
           local_wda_no = `Board Number`,
           `Exit Date` = mdy_hm(`Exit Date`)) %>% 
    filter(Program %in% all_funds) %>% 
    distinct(`TWIST ID`,Program, .keep_all = TRUE) %>% 
  mutate(Quarter = case_when(`Exit Date` <= '2021-03-31' ~ "Q1",
                             `Exit Date` <= '2021-06-30' ~ "Q2",
                             `Exit Date` <= '2021-09-30' ~ "Q3",
                             TRUE ~ "Q4"),.after = `Exit Date`) %>% 
    group_by(`Participation Period Id`, Program) %>%
    arrange(`Participation Period Id`, Program,desc(`Texas Credential Numerator`)) %>%
    distinct(`Participation Period Id`, `Population Group Code`,.keep_all = TRUE) %>%
    ungroup()

```


## {.tabset .tabset-pills}

### Summary
```{r}
X_Summary(19)
X_Summary_All(19)
```

### Summary By Quarter
```{r}
X_Summary_Qtr(19)
```

### Employed Quarter 2
```{r}
X_EQ2(19,"Adult")
X_EQ2(19,"DW")
```

### Employed Quarter 4
```{r}
X_EQ4(19,"Adult")
X_EQ4(19,"DW")
```

### Employed Enrolled Quarter 2
```{r}
X_EEQ2(19,"Youth")
```

### Employed Enrolled Quarter 4
```{r}
X_EEQ4(19,"Youth")
```

### Employed Enrolled Quarter 2 - 4
```{r}
X_EEQ2_4(19)
```

### Credential Rate
```{r}
x_cred_adult(19)
x_cred_DW(19)
x_cred_youth(19)
```

### MSG Rate
```{r}
x_msg_adult(19)
x_msg_dw(19)
x_msg_youth(19)
```

### Data {.tabset .tabset-pills}

#### Employed Q2
```{r}
# All_Data <- rbind(EQ2,EQ4,EEQ2,EEQ4,EEQ2_Q4,EQ2_Q4)

X_data_tbl(EQ2,"Employed Q2")
```

#### Employed Q4
```{r}
X_data_tbl(EQ4,"Employed Q4")
```

#### Employed Enrolled Q2
```{r}
X_data_tbl(EEQ2,"Employed Enrolled Q2")
```

#### Employed Enrolled Q4
```{r}
X_data_tbl(EEQ4,"Employed Enrolled Q4")
```

#### Employed Enrolled Q2 - Q4
```{r}
X_data_tbl(EEQ2_Q4,"Employed Enrolled Q2 - Q4")
```

#### Credential
```{r}
credentials %>% 
    select(`TWIST ID`,`Exit Date`,local_wda_no,Program,`Texas Credential Numerator`) %>% 
    mutate_all(as.factor) %>% 
    datatable(rownames = FALSE,
              filter = 'top',
              colnames = c("TWIST","Exit Date","Board","Population","Numerator"),
              extensions = 'Buttons',options=
              list(dom='Blfrtip',
                   autoWidth=TRUE,
                   buttons=c('pdf','excel')))
```

#### Measurable Skills Gain
```{r}
MSG %>% 
    # filter(WDA_NO %in% areas) %>% 
    select(`Customer Id`, `MSG End Date`, WDA_NO,Population_Desc, `MSG Numerator` ) %>% 
    mutate_all(as.factor) %>% 
    datatable(rownames = FALSE,
                caption = paste("Table"),
                filter = 'top',
                colnames = c("TWIST","Exit Date","Board","Population","Numerator"),
                extensions = 'Buttons',options=
                list(dom='Blfrtip',
                     autoWidth=TRUE,
                     buttons=c('pdf','excel')))
```

```{r eval=FALSE, include=FALSE}
# path <- "H:/Performance Project/Functions/Functions.R"
# 
# file_header_text <- str_glue("
# # Libraries
# library(tidyverse)
#          ")
# 
# write_lines(file_header_text, file  = path)
# 
# lsf.str() %>% 
#     dump(file = path,append = TRUE)

```

